sudo:  required
services:
  - docker

before_install:
  - docker build -t techsivam/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run techsivam/react-test npm run test -- --coverage

after_success:
  - docker build -t techsivam16/multi-client ./client
  - docker build -t techsivam16/multi-nginx ./nginx
  - docker build -t techsivam16/multi-server ./server
  - docker build -t techsivam16/multi-worker ./worker
  #login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to docker hub
  - docker push techsivam16/multi-client
  - docker push techsivam16/multi-nginx
  - docker push techsivam16/multi-server
  - docker push techsivam16/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-637336585858"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
